version: "3.6"

services:
  postgres:
    image: postgres:11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 15432:5432
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .env
    volumes:
      - .:/app
      - bundler:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - postgres
  redis:
     image: redis:alpine
     volumes:
       - ./tmp/db:/var/lib/redisdata/data
     ports:
       - 6379:6379
volumes:
  bundler: {}
